permissions:
  issues: write
  pull-requests: write

on:
  pull_request_target:
    types: [opened, reopened, synchronize]
    branches: [main]

jobs:
  branch-name-check:
    name: Check Branch Name
    runs-on: ubuntu-latest
    outputs:
      name_check: ${{ steps.check-name.outputs.name_check }}
    steps:
      - name: Check if branch name contains only English characters
        id: check-name
        run: |
          BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
          if [[ "$BRANCH_NAME" =~ ^[a-zA-Z]+$ ]]; then
            echo "name_check=true" >> $GITHUB_OUTPUT
          else
            echo "name_check=false" >> $GITHUB_OUTPUT
          fi

  comment:
    name: Comment on PR
    runs-on: ubuntu-latest
    needs: branch-name-check
    if: always()
    steps:
      - name: Post result comment
        uses: actions/github-script@v6
        with:
          github-token: ${{ github.token }}
          script: |
            const okName = '${{ needs.branch-name-check.outputs.name_check }}' === 'true';
            let body = '## 英文内容检查结果\n\n';
            if (okName) {
              body += '✅ **分支名检查:** 通过！\n\n';
              body += '🎉 **全部通过！**';
            } else {
              body += '❌ **分支名检查:** 失败！\n> 只允许英文字母。\n\n';
              body += '⚠️ **请修复后重新提交。**';
            }
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body
            });