name: Deploy Static Resources on Main Branch Update

on:
  push:
    branches:
      - main
    paths:
      - 'TCer/**'
      - 'script.js'
      - 'styles.css'
      - 'index.html'
      - '.github/workflows/update-pages.yml'
      - '.github/scripts/generate-cards.js'
      - 'package.json'
      - 'package-lock.json'

jobs:
  deploy-static-resources:
    runs-on: ubuntu-latest

    steps:
      # Step 1: 检出 main 分支
      - name: Checkout Main Branch
        uses: actions/checkout@v3
        with:
          ref: main

      # Step 2: 切换到 gh-pages 分支
      - name: Switch to gh-pages Branch
        run: |
          git fetch origin gh-pages
          git checkout gh-pages

      # Step 3: 设置 SSH 密钥
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Step 4: 列出工作区中的文件（调试用）
      - name: List files in workspace
        run: ls -R

      # Step 5: 将静态资源同步到服务器
      - name: Deploy Static Resources to Server
        run: |
          ssh -T -o StrictHostKeyChecking=no root@162.14.117.33 << 'EOF'
            echo "Current working directory:"
            pwd
            echo "Listing files in current directory:"
            ls -la
            cd /www/wwwroot/hello_technical_writing || mkdir -p /www/wwwroot/hello_technical_writing
            echo "Listing files in target directory before rsync:"
            ls -la /www/wwwroot/hello_technical_writing
            rsync -avz --delete ./ /www/wwwroot/hello_technical_writing/
            echo "Listing files in target directory after rsync:"
            ls -la /www/wwwroot/hello_technical_writing
            echo "Static resources have been updated on the server."
          EOF