name: Update GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'TCer/**'
      - 'script.js'
      - 'styles.css'
      - 'index.html'

jobs:
  update-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install marked
        
      - name: Generate cards
        run: |
          node -e "
            const fs = require('fs');
            const path = require('path');
            const marked = require('marked');
            
            const tcerDir = 'TCer';
            const cards = [];
            
            fs.readdirSync(tcerDir).forEach(file => {
              if (file.endsWith('.md')) {
                const content = fs.readFileSync(path.join(tcerDir, file), 'utf8');
                const html = marked.parse(content);
                const name = html.match(/<h1>(.*?)<\/h1>/)[1];
                const school = html.match(/<h2>(.*?)<\/h2>/)[1];
                const slogan = html.match(/<h3>(.*?)<\/h3>/)[1];
                
                cards.push({name, school, slogan});
              }
            });
            
            const scriptContent = fs.readFileSync('script.js', 'utf8');
            const newScript = scriptContent.replace(
              /const exampleData = {[^}]*}/,
              `const cardsData = ${JSON.stringify(cards)}`
            );
            
            fs.writeFileSync('script.js', newScript);
          "
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages 