name: Update GitHub Pages and Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'TCer/**'
      - 'script.js'
      - 'styles.css'
      - 'index.html'
      - '.github/workflows/update-pages.yml'
      - '.github/scripts/generate-cards.js'
      - 'package.json'
      - 'package-lock.json'

jobs:
  update-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Generate cards and update script.js
        id: generate
        run: node .github/scripts/generate-cards.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
      
      # 等待 gh-pages 分支更新
      - name: Wait for gh-pages to update
        run: sleep 30
      
      # 检出 gh-pages 分支
      - name: Checkout gh-pages Branch
        uses: actions/checkout@v3
        with:
          ref: 'gh-pages'
          path: 'gh-pages-content'
      
      # 部署到服务器
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2.1.7
        with:
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          remote_host: ${{ secrets.SSH_HOST }}
          remote_user: ${{ secrets.SSH_USERNAME }}
          source: "./gh-pages-content/"  # 从检出的gh-pages目录部署
          target: "/www/wwwroot/hello_technical_writing/"
          delete: true