name: On gh-pages Update

on:
  push:
    branches:
      - gh-pages

jobs:
  on-gh-pages-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages Branch
        uses: actions/checkout@v3

      # 其他自定义操作，例如部署到服务器
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2.1.7
        with:
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          remote_host: ${{ secrets.SSH_HOST }}
          remote_user: ${{ secrets.SSH_USERNAME }}
          source: "./"  # 要部署的文件
          target: "/www/wwwroot/hello_technical_writing/"
          delete: true