name: Deploy Static Resources on script.js Update

on:
  push:
    branches:
      - gh-pages
    paths:
      - 'script.js' # 仅当 script.js 文件发生变化时触发

jobs:
  deploy-static-resources:
    runs-on: ubuntu-latest

    steps:
      # Step 1: 检出整个仓库
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: gh-pages

      # Step 2: 设置 SSH 密钥
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Step 3: 将静态资源同步到服务器
      - name: Deploy Static Resources to Server
        run: |
          ssh -o StrictHostKeyChecking=no your-user@your-server-ip << 'EOF'
            cd /www/wwwroot/hello_technical_writing || mkdir -p /www/wwwroot/hello_technical_writing
            rsync -avz --delete ./ /www/wwwroot/hello_technical_writing/
            echo "Static resources have been updated on the server."
          EOF