name: Deploy to Server on gh-pages Update

on:
  push:
    branches:
      - gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: 检查出 gh-pages 分支
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        ref: gh-pages

    # Step 2: 设置 SSH 密钥
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    # Step 3: 部署到你的服务器
    - name: Deploy to Server
      run: |
        ssh -o StrictHostKeyChecking=no your-user@your-server-ip << 'EOF'
          cd /www/wwwroot/hello_technical_writing
          git pull origin gh-pages
          echo "Deployment completed!"
        EOF